[package]
name = "ctyp"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["HPDell <https://github.com/hpdell>"]
license = "MIT"
description = "A Typst package for Chinese typography."
categories = ["text", "languages", "utility"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
